apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  labels:
    app: my-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
      - name: my-container
        image: myrepo6473.azurecr.io/ravi-cont:fa3deca6db6d87188f8e95c9c190395d1c8d6b5d
        ports:
        - containerPort: 8080
